config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'
 devise_for :admins, path: 'admin',controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
 }
 scope module: :public do
 resource :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
  end
devise_for :customers, controllers: {
  sessions:      'public/sessions',
  passwords:     'public/passwords',
  registrations: 'public/registrations'
}

# devise_for(
#   :customers,
#   path: 'customers',
#   module: 'public',
#   skip: [:registration]
#   )

#   devise_scope :customers do
#     get 'customers/sign_up' => 'public/registrations#new'
#     post 'customers' => 'public/registrations#create'
#   end


 namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
 end

    scope module: :public do
    get 'homes/top' => 'homes#top'
    get 'homes/about' => 'homes#about'
    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    def total_price
	    self.item.with_tax_price * self.amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :is_deleted, inclusion: { in: [true, false] }
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image
  def with_tax_price
    (price * 1.1).floor
  end
end
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    def index
        @genres=Genre.all
        @genre=Genre.new
    end
    def create
        @genre=Genre.new(genre_params)
        if @genre.save
            redirect_to admin_genres_path
        end
    end
    def edit
      @genre=Genre.find(params[:id])
    end
    def update
      @genre=Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path(@genre)
    else
      @item=Genre.find(params[:id])
      render :edit
    end
    end
    private
      def genre_params
        params.require(:genre).permit(:name)
      end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.all.page(params[:page]).per(5)
  end

  def new
    @item=Item.new
  end

  def create
    @item=Item.new(item_params)
    if @item.save
      redirect_to admin_items_path(@item.id)
    else
      @item=Item.new
      render :new
    end
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
     @item=Item.find(params[:id])
    if @item.update(item_params)
       redirect_to admin_items_path(@item)
    else
       @item=Item.find(params[:id])
       render :edit
    end
  end
 private
 def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
 end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true
class Admin::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
      admin_homes_top_path
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="col-lg-2 text-center bg-light my-4">商品編集</h4>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <%= form_with model: @item,url: admin_item_path, local: true do |f| %>
      <div class="form-group">
          <%= f.label :商品画像%><br/>
          <%= f.attachment_field:image %>
　　　</div>
      <div class="form-group">
        <%= f.label :商品名 %><br/>
        <%= f.text_field:name %>
      </div>
　　　<div class="form-group">
        <%= f.label :商品説明 %><br/>
        <%= f.text_field:introduction %>
      </div>
      <div class="form-group">
        <%= f.label :ジャンル %><br/>
       <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
      </div>
      <div class="form-group">
      　<%= f.label :税抜価格 %><br/>
        <%= f.text_field:price %>
      </div>
      <div class="form-group">
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, "販売中", {value: true} %>
        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, "販売停止中", {value: false} %>
      </div>
      <div class="actions">
        <%= f.submit "変更を保存" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="header col-lg-2 text-center bg-light my-4 ml-5">商品一覧</h4>
      <div class="col-lg-2 text-center my-4 ml-auto">
        <%= link_to new_admin_item_path, class: 'text-dark' do %>
        <i class="fas fa-plus-circle"></i>
        <% end %>
      </div>
  </div>

<table class="table col-lg-10 mx-auto">
  <thead class="thead-light">
    <tr>
      <th>商品id</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= link_to item.name, admin_item_path(item) %></td>
      <td><%= item.price %></td>
      <td><%= item.genre.name%></td>
      <td><%= item.is_active ? '販売中' : '販売停止中' %></td>
    </tr>
    <% end %>
  </tbody>
 </table>
<div class="offset-md-5 col-md-2"><%= paginate @items%></div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <h4 class="col-lg-2 text-center bg-light my-4">商品新規登録</h4>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <%= form_with model: @item,url: admin_items_path, local: true do |f| %>
      <div class="form-group">
          <%= f.label :商品画像%><br/>
          <%= f.attachment_field :image %>
      </div>
      <div class="form-group">
        <%= f.label :商品名 %><br/>
        <%= f.text_field:name %>
      </div>
      <div class="form-group">
        <%= f.label :商品説明 %><br/>
        <%= f.text_field:introduction %>
      </div>
      <div class="form-group">
        <%= f.label :ジャンル %><br/>
       <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
      </div>
      <div class="form-group">
        <%= f.label :税抜価格 %><br/>
        <%= f.text_field:price %>
      </div>
      <div class="form-group">
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, "販売中", {value: true} %>
        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, "販売停止中", {value: false} %>
      </div>
      <div class="actions">
        <%= f.submit "新規登録", class: "btn btn-success btn-lg"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="col-lg-2 text-center bg-light my-4">商品詳細</h4>
  </div>
  <div class="row">
    <div class="col-lg-3">
      <%= attachment_image_tag @item, :image, :fill,60,60 %>
    </div>
    <div class="col-lg-offset-1 col-lg-8">
      <table class="table-noborder">
        <!--%= form_with model: @item,url: admin_items_path, local: true do |f| %>-->
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>
        <tr >
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <td>税込価格（税抜価格）</td>
          <td><%= @item.price %></td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td><%= @item.is_active ? '販売中' : '販売停止中' %></td>
        </tr>
      </table>
      <%= link_to "編集",edit_admin_item_path(@item),class:"btn btn-success btn-lg"%>
    </div>
  </div>
</div>