config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'
 devise_for :admins, path: 'admin',controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
 }
 scope module: :public do
 resource :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
  end
devise_for :customers, controllers: {
  sessions:      'public/sessions',
  passwords:     'public/passwords',
  registrations: 'public/registrations'
}

# devise_for(
#   :customers,
#   path: 'customers',
#   module: 'public',
#   skip: [:registration]
#   )

#   devise_scope :customers do
#     get 'customers/sign_up' => 'public/registrations#new'
#     post 'customers' => 'public/registrations#create'
#   end


 namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
 end

    scope module: :public do
    get 'homes/top' => 'homes#top'
    get 'homes/about' => 'homes#about'
    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    def total_price
	    self.item.with_tax_price * self.amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :is_deleted, inclusion: { in: [true, false] }
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image
  def with_tax_price
    (price * 1.1).floor
  end
end
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    def  index
        @customers=Customer.all.page(params[:page]).per(3)

    end
    def  show
        @customer=Customer.find(params[:id])
    end
    def  edit
        @customer=Customer.find(params[:id])
    end
    def update
        @customer=Customer.find(params[:id])
    if@customer.update(customer_params)
        redirect_to admin_customers_path(@customer)
    else
      @customer=Customer.find(params[:id])
      render :edit
    end
    end
    private
      def customer_params
        params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :postal_code, :address, :telephone_number, :is_deleted)
      end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.all.page(params[:page]).per(5)
  end

  def new
    @item=Item.new
  end

  def create
    @item=Item.new(item_params)
    if @item.save
      redirect_to admin_items_path(@item.id)
    else
      @item=Item.new
      render :new
    end
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
     @item=Item.find(params[:id])
    if @item.update(item_params)
       redirect_to admin_items_path(@item)
    else
       @item=Item.find(params[:id])
       render :edit
    end
  end
 private
 def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="header col-lg-4 text-center bg-light my-4 ml-5"><%= @customer.last_name+@customer.first_name %>さんの会員詳細</h4>
  </div>

<div class="row">
    <div class="col-lg-12">
    <%= form_with model: @customer,url: admin_customer_path , local: true do |f| %>
      <div class="form-group">
          <%= f.label :会員ID%>
           <%= f.text_field:id%>
　　　</div>
      <div class="form-group">
        <%= f.label :氏名 %>
        <%= f.text_field:last_name%>
        <%= f.text_field:first_name%>
      </div>
      <div class="form-group">
        <%= f.label :フリガナ %><br/>
        <%= f.text_field:last_name_kana%>
        <%= f.text_field:first_name_kana%>
      </div>
      <div class="form-group">
      　<%= f.label :郵便番号 %><br/>
        <%= f.text_field:postal_code %>
      </div>
       <div class="form-group">
      　<%= f.label :住所 %><br/>
        <%= f.text_field:address %>
      </div>
       <div class="form-group">
      　<%= f.label :電話番号 %><br/>
        <%= f.text_field:telephone_number %>
      </div>
      <div class="form-group">
      　<%= f.label :メールアドレス %><br/>
        <%= f.text_field:email %>
      </div>
      <div class="form-group">
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, "有効", {value: true} %>
        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, "退会", {value: false} %>
      </div>
      <div class="actions">
        <%= f.submit "変更を保存" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="header col-lg-2 text-center bg-light my-4 ml-5">会員一覧</h4>
  </div>

  <table class="col-lg-10 mx-auto">
    <thead class="thead-light">
      <tr>
        <th>会員id</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to customer.last_name, admin_customer_path(customer) %><%= customer.first_name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.is_deleted ? '退会' : '有効' %></td>
      </tr>
      <% end %>
    </tbody>
 </table>
 <div class="offset-md-5 col-md-2"><%= paginate @customers%></div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="header col-lg-2 text-center bg-light my-4 ml-5">
    <%= @customer.last_name+@customer.first_name %>さんの会員詳細</h4>
  </div>

  <h5>会員ID</h5>
  <p><%= @customer.id %></p>
  <h5>氏名</h5>
  <p><%= @customer.last_name+@customer.first_name %></p>
  <h5>フリガナ</h5>
  <p><%= @customer.last_name_kana+@customer.first_name_kana %></p>
  <h5>郵便番号</h5>
  <p><%=@customer.postal_code %></p>
  <h5>住所</h5>
  <p><%=@customer.address %></p>
  <h5>電話番号</h5>
  <p><%=@customer.telephone_number %></p>
  <h5>メールアドレス</h5>
  <p><%= @customer.email %></p>
  <h5>会員ステータス</h5>
  <p><%= @customer.is_deleted ? '退会' : '有効'%></p>
  <%= link_to "編集",edit_admin_customer_path(@customer), class:"btn btn-success"%>
  <%= link_to "注文履歴一覧を見る",admin_homes_top_path, class:"btn btn-success"%>