config/routes.rb
Rails.application.routes.draw do
  root to: 'public/homes#top'
 devise_for :admins, path: 'admin',controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
 }
 scope module: :public do
 resource :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
  end
devise_for :customers, controllers: {
  sessions:      'public/sessions',
  passwords:     'public/passwords',
  registrations: 'public/registrations'
}

# devise_for(
#   :customers,
#   path: 'customers',
#   module: 'public',
#   skip: [:registration]
#   )

#   devise_scope :customers do
#     get 'customers/sign_up' => 'public/registrations#new'
#     post 'customers' => 'public/registrations#create'
#   end


 namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
 end

    scope module: :public do
    get 'homes/top' => 'homes#top'
    get 'homes/about' => 'homes#about'
    resources :items, only: [:index, :show]

    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    def total_price
	    self.item.with_tax_price * self.amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :is_deleted, inclusion: { in: [true, false] }
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image
  def with_tax_price
    (price * 1.1).floor
  end
end
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    def index
        @genres=Genre.all
        @genre=Genre.new
    end
    def create
        @genre=Genre.new(genre_params)
        if @genre.save
            redirect_to admin_genres_path
        end
    end
    def edit
      @genre=Genre.find(params[:id])
    end
    def update
      @genre=Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path(@genre)
    else
      @item=Genre.find(params[:id])
      render :edit
    end
    end
    private
      def genre_params
        params.require(:genre).permit(:name)
      end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.all.page(params[:page]).per(5)
  end

  def new
    @item=Item.new
  end

  def create
    @item=Item.new(item_params)
    if @item.save
      redirect_to admin_items_path(@item.id)
    else
      @item=Item.new
      render :new
    end
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
     @item=Item.find(params[:id])
    if @item.update(item_params)
       redirect_to admin_items_path(@item)
    else
       @item=Item.find(params[:id])
       render :edit
    end
  end
 private
 def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <h3 class="col-lg-3 text-center bg-light my-5 ml-5">ジャンル編集</h3>
  </div>
  <div class="row">
    <div class="form-inline">
    <%= form_with model: @genre,url: admin_genre_path, local: true do |f| %>
      <div class="form-group">
        <%= f.label:ジャンル名%>
        <%= f.text_field:name%>
         <%= f.submit "変更を保存", class:"btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="col-lg-3 text-center bg-light my-4 ml-5">ジャンル一覧・追加</h3>
  </div>
  <div class="row">
    <div class="form-inline">
    <%= form_with model: @genre,url: admin_genres_path, local: true do |f| %>
      <div class="form-group">
        <%= f.label:ジャンル名, class:"ml-5"%>
        <%= f.text_field:name, class:"form-text my-5 mx-5" %>
        <%= f.submit "新規登録", class:"btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
  <table class="table col-lg-4 mt-4">
  <thead class="thead-light">
    <tr>
      <th colspan="2">ジャンル</th>
    </tr>
  </thead>
  <% @genres.each do |genre| %>
  <tbody>
    <tr>
      <td><%= genre.name %></td>
      <td><%= link_to "編集",edit_admin_genre_path(genre), class:"btn btn-success"%></td>
    </tr>
  </tbody>
  <% end %>
 </table>
</div>

app/views/admin/homes/about.html.erb
<div class="container">
  <div class="col">
    <h1 class="text-center">About</h1>
  </div>
  <div class="col">
    <p class="text-center">
      ながのCAKEは全国発送可能なケーキ屋さんです。</br>
      お子様からお年寄りの方までお召し上がりいただけるよう、</br>
      さまざまなバリデーションをご用意しています。</br>
      また全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。</br>
      ぜひご注文ください。。</br>
    </p>
  </div>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <h4 class="col-lg-2 text-center bg-light my-4 ml-5">注文履歴一覧</h4>
  </div>

<table class="col-lg-10 mx-auto">
  <thead>
    <tr>
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文個数</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
    <tr>
      <td><%= link_to order.created_at, admin_order_path(order) %></td>
      <td><%= order.customer.last_name %></td>
      <td><%= order.order_details.count %></td>
    </tr>
    <% end %>
  </tbody>
 </table>
</div>